<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>52f1b8a1-bc55-4fd1-8b40-f0de4f32e2ed</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Stripe.net" Version="52.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AiCallAssistent.Application\AiCallAssistent.Application.csproj" />
    <ProjectReference Include="..\AiCallAssistent.Infrastructure\AiCallAssistent.Infrastructure.csproj" />
  </ItemGroup>

</Project>
